### ISSUE TITLE
Question about the inference phase #21

### ISSUE THREAD

**Issue by JoinWorldMC** [lhoyer/HRDA#22] opened 2022-09-27 17:56 UTC
@lhoyer 

Appreciate your kindness.
You're right. What I want to know is the forward pass.

Can you cross check if the calculation is correct?

**Case1.**
If not using sliding window LR context crop, config is as follows:
`[1]test_cfg=dict(mode='whole'))
`If not using sliding window HR detail crop, config is as follows:
`[2]hr_slide_inference=False,
`

**In case 1, The number of forward passes is 160M?**
*160M = 60M(Encoder(LR Crop)) + 20M(Decoder(LR Crop)) + 60M(Encoder(HR Crop)) + 20M(Decoder(HR crop))

Because if hr_slide_inference and sliding window inference are not used, the whole image is used for LR context crop and HR detail crop.

Also, am I wrong to think that HRDA is a resolution-based ensemble method?

**Comment by lhoyer** [comment] 2022-09-29 07:14
Duplicate of #21.

**Closed as completed by lhoyer** 2022-09-29 07:14 UTC
Labels: duplicate
